from typing import Protocol

class Transport(Protocol):
    async def receive_audio(self) -> bytes | None: ...
    async def send_audio(self, pcm24k: bytes) -> bytes | None: ...
    async def clear_playback(self) -> None: ...
    async def send_event(self, event: dict) -> None: ...
    async def finish(self) -> None: ...